export const GENERAL_ELECTION = 'GENERAL_ELECTION';
export const FLORIDA_SENATE = 'FLORIDA_SENATE';


// Election Keywords
export const ECONOMY = 'ECONOMY'
export const ECONOMY_A_FAIR_TAX_SYSTEM = 'ECONOMY_A_FAIR_TAX_SYSTEM'
export const ECONOMY_FIXING_AMERICAS_INFRASTRUCTURE = 'ECONOMY_FIXING_AMERICAS_INFRASTRUCTURE'
export const ECONOMY_MANUFACTURING = 'ECONOMY_MANUFACTURING'
export const ECONOMY_SMALL_BUSINESS = 'ECONOMY_SMALL_BUSINESS'
export const ECONOMY_SOCIAL_SECURITY_AND_MEDICARE = 'ECONOMY_SOCIAL_SECURITY_AND_MEDICARE'
export const ECONOMY_WALL_STREET_REFORM = 'ECONOMY_WALL_STREET_REFORM'
export const ECONOMY_WORKS_FOR_EVERYONE = 'ECONOMY_WORKS_FOR_EVERYONE'
export const ECONOMY_REGULATION = 'ECONOMY_REGULATION'
export const ECONOMY_TAXPLAN = 'ECONOMY_TAXPLAN'
export const ECONOMY_TRADE = 'ECONOMY_TRADE'

export const ECONOMY_FARMERS_RANCHERS = 'ECONOMY_FARMERS_RANCHERS'
export const IMPROVING_EDUCATION = 'IMPROVING_EDUCATION'
export const EDUCATION_COMMON_CORE = 'EDUCATION_COMMON_CORE'

export const EDUCATION = 'EDUCATION'
export const EDUCATION_CAMPUS_SEXUAL_ASSULT = 'EDUCATION_CAMPUS_SEXUAL_ASSULT'
export const EDUCATION_COLLEGE_DEBT = 'EDUCATION_COLLEGE_DEBT'
export const EDUCATION_EARLY_CHILDHOOD = 'EDUCATION_EARLY_CHILDHOOD'
export const EDUCATION_K_12 = 'EDUCATION_K_12'
export const EDUCATION_TECHNOLOGY_AND_INNOVATION = 'EDUCATION_TECHNOLOGY_AND_INNOVATION'

export const ENVIRONMENT = 'ENVIRONMENT'
export const ENVIRONMENT_CLIMATE_CHANGE = 'ENVIRONMENT_CLIMATE_CHANGE'
export const ENVIRONMENT_PROTECTING_ANIMALS_AND_WILDLIFE = 'ENVIRONMENT_PROTECTING_ANIMALS_AND_WILDLIFE'
export const ENVIRONMENT_RURAL_COMMUNITIES = 'ENVIRONMENT_RURAL_COMMUNITIES'
export const ENVIRONMENT_ENERGY = 'ENVIRONMENT_ENERGY'

export const ENVIRONMENT_OUR_ENVIRONMENT = 'ENVIRONMENT_OUR_ENVIRONMENT'

export const EQUALITY = 'EQUALITY'
export const EQUALITY_CAMPAIGN_FINANCE_REFORM = 'EQUALITY_CAMPAIGN_FINANCE_REFORM'
export const EQUALITY_CRIMINAL_JUSTICE_REFORM = 'EQUALITY_CRIMINAL_JUSTICE_REFORM'
export const EQUALITY_IMMIGRATION_REFORM = 'EQUALITY_IMMIGRATION_REFORM'
export const EQUALITY_LFBT_RIGHTS_AND_EQULITY = 'EQUALITY_LFBT_RIGHTS_AND_EQULITY'
export const EQUALITY_RACIAL_JUSTICE = 'EQUALITY_RACIAL_JUSTICE'
export const EQUALITY_VOTING_RIGHTS = 'EQUALITY_VOTING_RIGHTS'
export const EQUALITY_WOMENS_RIGHTS_AND_OPPORTUNITY = 'EQUALITY_WOMENS_RIGHTS_AND_OPPORTUNITY'
export const EQUALITY_GUN_CONTROL = 'EQUALITY_GUN_CONTROL'

export const EQUALITY_SENIORS = 'EQUALITY_SENIORS'

export const HEALTH = 'HEALTH'
export const HEALTH_ADDICATION_AND_SUBSTANCE_USE = 'HEALTH_ADDICATION_AND_SUBSTANCE_USE'
export const HEALTH_AN_END_T0_ALZHEIMERS = 'HEALTH_AN_END_T0_ALZHEIMERS'
export const HEALTH_AUTISM = 'HEALTH_AUTISM'
export const HEALTH_DISABILITY_RIGHTS = 'HEALTH_DISABILITY_RIGHTS'
export const HEALTH_HEALTH_CARE = 'HEALTH_HEALTH_CARE'
export const HEALTH_HIV_AND_AIDS = 'HEALTH_HIV_AND_AIDS'
export const HEALTH_CHILD_CARE = 'HEALTH_CHILD_CARE'

export const JOBS = 'JOBS'
export const JOBS_PAID_FAMILY_AND_MEDICAL_LEAVE = 'JOBS_PAID_FAMILY_AND_MEDICAL_LEAVE'
export const JOBS_LABOR_AND_WORKERS_RIGHTS = 'JOBS_LABOR_AND_WORKERS_RIGHTS'
export const JOBS_VETERANS_THE_ARMED_FORCES_AND_THEIR_FAMILIES = 'JOBS_VETERANS_THE_ARMED_FORCES_AND_THEIR_FAMILIES'
export const JOBS_WAGES = 'JOBS_WAGES'
export const JOBS_WORKFORCE_SKILLS_AND_JOBS_TRAINING = 'JOBS_WORKFORCE_SKILLS_AND_JOBS_TRAINING'

export const SECURITY = 'SECURITY'
export const SECURITY_COMBATING_TERRORISM = 'SECURITY_COMBATING_TERRORISM'
export const SECUTIRY_GUN_VIOLENCE = 'SECUTIRY_GUN_VIOLENCE'
export const SECURITY_MILITARY_AND_DEFENSE = 'SECURITY_MILITARY_AND_DEFENSE'
export const SECURITY_NATIONAL_SECURITY = 'SECURITY_NATIONAL_SECURITY'
export const SECURITY_FOREGIN_POLICY = 'SECURITY_FOREGIN_POLICY'





 